# stage-1 build artifact
FROM amazoncorretto:17-alpine3.19 as builder
WORKDIR /app
ADD fintech-bank .
RUN ["./gradlew","bootJar"]

# stage-2 running image
FROM gcr.io/distroless/java17-debian12:latest
WORKDIR /app
COPY --from=builder /app/build/libs/fintech-bank-0.0.1-SNAPSHOT.jar fintech-bank-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "fintech-bank-0.0.1-SNAPSHOT.jar"]





